### ISSUE TITLE
Minecraft 1.20.5+ needs Java 21+

### ISSUE THREAD

**Issue by jayonthenet** [TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate#31]
Newer MC versions won't run because of Java 19 being used as the baseline. Tested with `-e 1.20.5` and `-e 1.20.6`. Leads to the following error during container start:

```shell
ViaVersion is up to date
Starting Minecraft server...
Starting org.bukkit.craftbukkit.Main
Exception in thread "ServerMain" java.lang.UnsupportedClassVersionError: org/bukkit/craftbukkit/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 63.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:38)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by NemoN** [comment]
see pull request https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate/pull/32

**Comment by jayonthenet** [comment]
Added a PR that updates MC to 1.20.6 and Java to 21 - see #33

**Comment by johnholton0** [comment]
I'm experiencing this issue as well with running the container and getting my kids' tablets running Bedrock to connect. Can't force the container to run newer versions because of the Java 21 issue.

**Comment by jayonthenet** [comment]
Seems like this is solved now. Will close this issue.
